### ISSUE TITLE
Component labels on the PCB not on silkscreen

### ISSUE THREAD

**Issue by repetto74** [stahlnow/atari-video-mod#1]
Hi,
Thank you for this project which looks nice and would like to build the pcb for s-video on the Atari 2600.
There is no marking on the PCB for the components labels listed in the BOM. How I am supposed to know where each components goes? Although it is pretty obvious for the IC's it is more complicated for resistors and caps.
Kind regards,
Rick

**Comment by stahlnow** [comment]
hello! thanks for your interest in building one! i added two pdf (schematics and placement) that will help you with the assembly. kind regards, stahl
