### ISSUE TITLE
Audio Amplifier question

### ISSUE THREAD

**Issue by Metacrack** [stahlnow/atari-video-mod#2]
Hello,
really interesting project!
I have one question about the routing of the amplifier.
Are pin 2 and 3 of JP1 supposed to be shorted to get the signal amplified?
Thank you

**Comment by stahlnow** [comment]
Hi! 
No, they should not be shorted. You can see the connections in the schematics:
https://github.com/stahlnow/atari-video-mod/blob/master/atari-2600-video-mod-v1.0_schematics.pdf

I think I might still have PCBs. If you are interested, I can send you one.

Cheers!

**Comment by Metacrack** [comment]
Thank you for your reply!
So, maybe it's a noob question but, looking at the schematic I understand that on Pin 1 of JP1 you have the audio signal coming from TIA13 and this signal should be amplified by the LM386. But the input signal of LM386 is only connected to Pin 2 of JP1...I supposed this signal should be routed to the input.
What's coming out from AUDIO?

Ciao, Gianluca

**Comment by stahlnow** [comment]
Hi!

I get the confusion now... at JP1 a volume potentiometer should be connected. I missed designating this in the schematics.

So Audio is coming from TIA13 through the audio amp / volume potentiometer. M04X2 is the output, a pinheader that you can connect RCA jacks, ie. a yellow one for composite video signal and a red one for audio.

Hope this clears things up!

Cheers!

**Comment by Metacrack** [comment]
Now I got it!
Thank you
